1 Numpy Arrays


In [ ]:
#1D arramge
import numpy as np

In [ ]:
mylist = [1,2,3,4,5]
print(mylist)

[1, 2, 3, 4, 5]


In [ ]:
#this is a 1D array
np.array(mylist)

array([1, 2, 3, 4, 5])

In [ ]:
#two dimension array
my_mat = [[1,2,3],[4,5,6],[7,8,9,]]

In [ ]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
#linspace a range from 0 to 5 with 10 evenly spaced numbers
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [ ]:
# eye - to create identitive matrix
np.eye(5,6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [ ]:
#array of uniform - array of random samples of uniform distribution from 0 to 1
np.random.rand(5)

array([0.8543632 , 0.25880436, 0.35227264, 0.59432194, 0.78127094])

In [ ]:
#two dimensional random sample uniform distribution 0 to 1
np.random.rand(4,4)

array([[0.40112587, 0.02700303, 0.5794327 , 0.46642186],
       [0.96421149, 0.55694393, 0.07477719, 0.98765155],
       [0.08891866, 0.47932357, 0.39658365, 0.29561254],
       [0.46328681, 0.17392302, 0.08854588, 0.34599531]])

In [ ]:
#standard normal discution or gaussion distribution
np.random.randn(4)

array([-0.40706234,  0.33042347,  0.27457006,  0.78571633])

In [ ]:
np.random.randn(4,5)

array([[-0.24078362, -0.54808991,  0.70384666, -0.53498826, -0.20404234],
       [ 0.71864479, -1.33123747, -0.25332878,  1.84976953, -0.73969183],
       [-0.37236601,  0.37667249,  2.37146231,  1.82667686,  1.46664704],
       [ 1.86045298, -1.36791217, -0.4730045 ,  1.61677196, -1.14534925]])

In [ ]:
#random numbers
np.random.randint(0,100)

77

In [ ]:
#random numbers 5 random numbers
np.random.randint(0,100,5)

array([36, 48, 65, 53, 50])

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#max and min
rand_arr = np.random.randint(0,50,10)

In [ ]:
rand_arr

array([ 2, 13, 40, 36, 46, 42, 12, 27, 37, 28])

In [ ]:
rand_arr.max()

46

In [ ]:
rand_arr.min()

2

In [ ]:
rand_arr.argmax()

4

In [ ]:
rand_arr.argmin()

0

In [ ]:
arr.shape

(25,)

In [ ]:
b = arr.reshape(5,5)

In [ ]:
b.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#indexing and selection

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:2]

array([10, 11])

In [ ]:
arr[5]

15

In [ ]:
arr[:5]

array([10, 11, 12, 13, 14])

In [ ]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [ ]:
#broadcasting values
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
slica_array = arr[0:6]

In [ ]:
slica_array

array([10, 11, 12, 13, 14, 15])

In [ ]:
slica_array[:] = 99

In [ ]:
slica_array

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr[:] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_copy

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr = np.arange(0,10)

In [ ]:
slice = arr[0:5]

In [ ]:
slice

array([0, 1, 2, 3, 4])

In [ ]:
slice[:] = 200

In [ ]:
slice

array([200, 200, 200, 200, 200])

In [ ]:
arr_cp1 = arr.copy()

In [ ]:
arr_cp1[:] = 200

In [ ]:
arr

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9])

In [ ]:
#index 2D

In [ ]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[0,0]

5

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
b = arr>5

In [ ]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
#numpy operations

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
#universal array functions
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)

10

In [ ]:
np.min(arr)

0

In [ ]:
arr.min()

0

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
import pandas as pd

In [ ]:
#create series
my_data = [10,20,30,40,50,60]
labels = ['a','b','c','d','e']

In [ ]:
pd.Series(my_data)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

PANDAS

In [ ]:
#dataframes

import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(data= randn(5,4), index=['a','b', 'c','d','e'],columns=['w','x','y','z'])

In [ ]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#indexing and selection
df['w']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [ ]:
type(df['w'])

pandas.core.series.Series

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#select multiple columns
df[['x','y']]

x         y
a  0.628133  0.907969
b -0.319318 -0.848077
c  0.740122  0.528813
d -0.758872 -0.933237
e  1.978757  2.605967

In [ ]:
type(df[['x','y']])

pandas.core.frame.DataFrame

In [ ]:
#add a new column

In [ ]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['new'] = df['w'] + df['x']

In [ ]:
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.334983
b  0.651118 -0.319318 -0.848077  0.605965  0.331800
c -2.018168  0.740122  0.528813 -0.589001 -1.278046
d  0.188695 -0.758872 -0.933237  0.955057 -0.570177
e  0.190794  1.978757  2.605967  0.683509  2.169552

In [ ]:
#remove columns and rows
#remove column using drop method

df.drop(labels='new', axis=1)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.334983
b  0.651118 -0.319318 -0.848077  0.605965  0.331800
c -2.018168  0.740122  0.528813 -0.589001 -1.278046
d  0.188695 -0.758872 -0.933237  0.955057 -0.570177
e  0.190794  1.978757  2.605967  0.683509  2.169552

In [ ]:
#to remove permanently put inplace=True
df.drop(labels='new', axis=1, inplace=True)

In [ ]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#remove a row
df.drop('b', axis=0)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#remove a row permanently
df.drop('b', axis=0 , inplace=True)

In [ ]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#select a row
df.loc['c']

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: c, dtype: float64

In [ ]:
type(df.loc['c'])

pandas.core.series.Series

In [ ]:
#select subset of rowns and columns
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.loc['c','x']

0.7401220570561068

In [ ]:
df.loc[['d','e'],['x','z']]

x         z
d -0.758872  0.955057
e  1.978757  0.683509

In [ ]:
np.random.seed(101)

In [ ]:
df2 = pd.DataFrame(data= randn(5,4), index=['a','b', 'c','d','e'],columns=['w','x','y','z'])

In [ ]:
df2

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#conditional selection
df2>0

w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [ ]:
b = df2>0

In [ ]:
b

w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [ ]:
df2[b]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df2[df2>0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
df2['w'] > 0

a     True
b     True
c    False
d     True
e     True
Name: w, dtype: bool

In [ ]:
df2[df2['w']>1]

w         x         y         z
a  2.70685  0.628133  0.907969  0.503826

In [ ]:
d = df2>1

In [ ]:
df2[d]

w         x         y   z
a  2.70685       NaN       NaN NaN
b      NaN       NaN       NaN NaN
c      NaN       NaN       NaN NaN
d      NaN       NaN       NaN NaN
e      NaN  1.978757  2.605967 NaN

In [ ]:
#multiple conditions at a time
df2

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#and operator
df2[(df2['w']>0)& (df2['y']>1)]

w         x         y         z
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
#or operator
df2[(df2['w']>0) | (df2['y']>1)]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [ ]:
# index
df2.reset_index()

index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [ ]:
new_index = ['R', 'G', 'B', 'O', 'Y']

In [ ]:
new_index

['R', 'G', 'B', 'O', 'Y']

In [ ]:
df2['Colors'] = new_index

In [ ]:
df2

w         x         y         z Colors
a  2.706850  0.628133  0.907969  0.503826      R
b  0.651118 -0.319318 -0.848077  0.605965      G
c -2.018168  0.740122  0.528813 -0.589001      B
d  0.188695 -0.758872 -0.933237  0.955057      O
e  0.190794  1.978757  2.605967  0.683509      Y

In [ ]:
df2.set_index('Colors')

w         x         y         z
Colors                                        
R       2.706850  0.628133  0.907969  0.503826
G       0.651118 -0.319318 -0.848077  0.605965
B      -2.018168  0.740122  0.528813 -0.589001
O       0.188695 -0.758872 -0.933237  0.955057
Y       0.190794  1.978757  2.605967  0.683509

In [ ]:
#multi index and index hierarchy
np.random.seed(101)

In [ ]:
outside = ['Red', 'Red', 'Red','Green','Green','Green']
inside = [1,2,3,1,2,3]

In [ ]:
hier_index = list(zip(outside,inside))

In [ ]:
hier_index

[('Red', 1), ('Red', 2), ('Red', 3), ('Green', 1), ('Green', 2), ('Green', 3)]

In [ ]:
multi_index = pd.MultiIndex.from_tuples(hier_index, names=['Colors','Numbers'])

In [ ]:
multi_index

MultiIndex([(  'Red', 1),
            (  'Red', 2),
            (  'Red', 3),
            ('Green', 1),
            ('Green', 2),
            ('Green', 3)],
           names=['Colors', 'Numbers'])

In [ ]:
df = pd.DataFrame(data= randn(6,2), index= multi_index, columns=['A',"B"])

In [ ]:
df

A         B
Colors Numbers                    
Red    1        2.706850  0.628133
       2        0.907969  0.503826
       3        0.651118 -0.319318
Green  1       -0.848077  0.605965
       2       -2.018168  0.740122
       3        0.528813 -0.589001

In [ ]:
df.loc['Red'].loc[1]

A    2.706850
B    0.628133
Name: 1, dtype: float64

In [ ]:
df.loc['Green']

A         B
Numbers                    
1       -0.848077  0.605965
2       -2.018168  0.740122
3        0.528813 -0.589001

In [ ]:
df.loc['Green'].loc[2]

A   -2.018168
B    0.740122
Name: 2, dtype: float64

In [ ]:
df.index.names

FrozenList(['Colors', 'Numbers'])

In [ ]:
df


A         B
Colors Numbers                    
Red    1        2.706850  0.628133
       2        0.907969  0.503826
       3        0.651118 -0.319318
Green  1       -0.848077  0.605965
       2       -2.018168  0.740122
       3        0.528813 -0.589001

In [ ]:
df.index.names = ['Col', 'Num']

In [ ]:
df

A         B
Col   Num                    
Red   1    2.706850  0.628133
      2    0.907969  0.503826
      3    0.651118 -0.319318
Green 1   -0.848077  0.605965
      2   -2.018168  0.740122
      3    0.528813 -0.589001

In [ ]:
#cross section
df

A         B
Col   Num                    
Red   1    2.706850  0.628133
      2    0.907969  0.503826
      3    0.651118 -0.319318
Green 1   -0.848077  0.605965
      2   -2.018168  0.740122
      3    0.528813 -0.589001

In [ ]:
 df.loc['Red']

A         B
Num                    
1    2.706850  0.628133
2    0.907969  0.503826
3    0.651118 -0.319318

In [ ]:
df.xs('Red')

A         B
Num                    
1    2.706850  0.628133
2    0.907969  0.503826
3    0.651118 -0.319318

In [ ]:
df.xs(1, level='Num')

A         B
Col                      
Red    2.706850  0.628133
Green -0.848077  0.605965

In [ ]:
#missing data
d = {"A": [1,2,np.nan], "B":[3,np.nan,np.nan],"C": [4,5,6]}

In [ ]:
d

{'A': [1, 2, nan], 'B': [3, nan, nan], 'C': [4, 5, 6]}

In [ ]:
d['A']

[1, 2, nan]

In [ ]:
df = pd.DataFrame(d)

In [ ]:
df

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [ ]:
#drop method
df.dropna()

A    B  C
0  1.0  3.0  4

In [ ]:
df.dropna(axis=1)

C
0  4
1  5
2  6

In [ ]:
df.dropna(thresh=2, axis=1)

A  C
0  1.0  4
1  2.0  5
2  NaN  6

In [ ]:
df.dropna(thresh=1, axis=1)

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [ ]:
df

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [ ]:
df.fillna(value="New Value")

A          B  C
0          1          3  4
1          2  New Value  5
2  New Value  New Value  6

In [ ]:
df['A'].fillna(value=df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [ ]:
df

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [ ]:
df

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [ ]:
team_data = {'Company':['Apple','Apple','FB', 'FB','Google','Google'],
             "Person":['Mark','Tom','John','Sara','Mia','Emma'],
             "Sales": [200,150,350,125,260,100]}

In [ ]:
team_data

{'Company': ['Apple', 'Apple', 'FB', 'FB', 'Google', 'Google'],
 'Person': ['Mark', 'Tom', 'John', 'Sara', 'Mia', 'Emma'],
 'Sales': [200, 150, 350, 125, 260, 100]}

In [ ]:
df = pd.DataFrame(team_data)

In [ ]:
df

Company Person  Sales
0   Apple   Mark    200
1   Apple    Tom    150
2      FB   John    350
3      FB   Sara    125
4  Google    Mia    260
5  Google   Emma    100

In [ ]:
b =df.groupby('Company')

In [ ]:
b.mean()

Sales
Company       
Apple    175.0
FB       237.5
Google   180.0

In [ ]:
b.std()

Sales
Company            
Apple     35.355339
FB       159.099026
Google   113.137085

In [ ]:
b.sum().loc['Apple']

Sales    350
Name: Apple, dtype: int64

In [ ]:
df.groupby(by='Company').sum().loc['FB']

Sales    475
Name: FB, dtype: int64

In [ ]:
b.count()

Person  Sales
Company               
Apple         2      2
FB            2      2
Google        2      2

In [ ]:
b.max()

Person  Sales
Company              
Apple      Tom    200
FB        Sara    350
Google     Mia    260

In [ ]:
b.min()

Person  Sales
Company              
Apple     Mark    150
FB        John    125
Google    Emma    100

In [ ]:
#group by method with describe
df.groupby(by='Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
Apple     2.0  175.0   35.355339  150.0  162.50  175.0  187.50  200.0
FB        2.0  237.5  159.099026  125.0  181.25  237.5  293.75  350.0
Google    2.0  180.0  113.137085  100.0  140.00  180.0  220.00  260.0

In [ ]:
#group by method with describe
df.groupby(by='Company').describe().transpose()

Company           Apple          FB      Google
Sales count    2.000000    2.000000    2.000000
      mean   175.000000  237.500000  180.000000
      std     35.355339  159.099026  113.137085
      min    150.000000  125.000000  100.000000
      25%    162.500000  181.250000  140.000000
      50%    175.000000  237.500000  180.000000
      75%    187.500000  293.750000  220.000000
      max    200.000000  350.000000  260.000000

In [ ]:
#merge join and concatenating

In [ ]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C0','C1','C2','C3'],
                  'D': ['D0','D1','D2','D3']},
                   index = [0, 1, 2, 3])
 
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B6','B7'],
                  'C':['C4','C5','C6','C7'],
                  'D':['D4','D5','D6','D7']},
                   index = [4, 5, 6, 7])
 
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B':['B8','B9','B10','B11'],
                  'C':['C8','C9','C10','C11'],
                  'D':['D8','D9','D10','D11']},
                   index = [8, 9, 10, 11])

In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat(objs=[df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat(objs=[df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
df4=pd.DataFrame({'Key':['K0','K1','K2','K3'],
                   'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3']})
 
df5=pd.DataFrame({'Key':['K0','K1','K2','K3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']})

In [ ]:
df4

Key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [ ]:
df5

Key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [ ]:
pd.merge(left=df4, right=df5, on='Key')

Key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [ ]:
df6 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
df7 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
df6

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [ ]:
df7

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [ ]:
pd.merge(left=df6, right=df7, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
df8 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3']},
                    index=['K0','K1','K2','K3'])
 
df9 = pd.DataFrame({'C':['C0','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']},
                    index=['K0','K1','K2','K3'])

In [ ]:
df8

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
K3  A3  B3

In [ ]:
df9

C   D
K0  C0  D0
K1  C1  D1
K2  C2  D2
K3  C3  D3

In [ ]:
df8.join(df9)

A   B   C   D
K0  A0  B0  C0  D0
K1  A1  B1  C1  D1
K2  A2  B2  C2  D2
K3  A3  B3  C3  D3

In [ ]:
d = {'col1':[1,2,3,4],
     'col2':[45,55,65,45],
     'col3':['asd','jkl','qwe','xyz']}

In [ ]:
df = pd.DataFrame(d)

In [ ]:
df

col1  col2 col3
0     1    45  asd
1     2    55  jkl
2     3    65  qwe
3     4    45  xyz

In [ ]:
df['col2'].unique()

array([45, 55, 65])

In [ ]:
len(df['col2'].unique())

3

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

45    2
55    1
65    1
Name: col2, dtype: int64

In [ ]:
def times5(x):
  return x*5

In [ ]:
times5(10)

50

In [ ]:
df[['col2','col1']].sum()

col2    210
col1     10
dtype: int64

In [ ]:
df['col1'].apply(times5)

0     5
1    10
2    15
3    20
Name: col1, dtype: int64

In [ ]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [ ]:
df.drop('col1',axis=1)

col2 col3
0    45  asd
1    55  jkl
2    65  qwe
3    45  xyz

In [ ]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [ ]:
df.sort_values('col2')

col1  col2 col3
0     1    45  asd
3     4    45  xyz
1     2    55  jkl
2     3    65  qwe

In [ ]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)