In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
print(tf.__version__)

2.3.0


In [ ]:
#data preprocessing
from sklearn import datasets, metrics

In [ ]:
#import the data set
cancer = datasets.load_breast_cancer()

In [ ]:
print(cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
#matrix of features
x = pd.DataFrame(data=cancer.data, columns=cancer.feature_names)

In [ ]:
x.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
#dependent variable
y = cancer['target']

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
x.shape, y.shape

((569, 30), (569,))

In [ ]:
#split train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [ ]:
x_train.shape

(455, 30)

In [ ]:
x_test.shape

(114, 30)

In [ ]:
#features scaling
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
x_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]])

In [ ]:
x_train.shape , x_test.shape

((455, 30), (114, 30))

In [ ]:
x_train = x_train.reshape(455,30,1)
x_test = x_test.reshape(114,30,1)

In [ ]:
x_train.shape

(455, 30, 1)

In [ ]:
x_test.shape

(114, 30, 1)

In [ ]:
#build the model
model = tf.keras.models.Sequential()

In [ ]:
#first layer CNN
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu', input_shape=(30,1)))

In [ ]:
#batch normalization
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
#dropout ( regularization technique)
model.add(tf.keras.layers.Dropout(0.20))

In [ ]:
#second layer CNN
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=2, activation='relu', ))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.40))

In [ ]:
#flatte
model.add(tf.keras.layers.Flatten())

In [ ]:
#dense layer ( full connected layer)
model.add(tf.keras.layers.Dense(units=64, activation='relu'))


In [ ]:
#output layer - binary output sigmoid
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 29, 32)            96        
_________________________________________________________________
batch_normalization (BatchNo (None, 29, 32)            128       
_________________________________________________________________
dropout (Dropout)            (None, 29, 32)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 28, 64)            4160      
_________________________________________________________________
batch_normalization_1 (Batch (None, 28, 64)            256       
_________________________________________________________________
dropout_1 (Dropout)          (None, 28, 64)            0         
_________________________________________________________________
flatten (Flatten)            (None, 1792)              0

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.00005)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics='accuracy')

In [ ]:
#training the model
history1 = model.fit(x_train, y_train, epochs=50, validation_data=(x_test,y_test))

Epoch 1/50
15/15 [==============================] - 0s 21ms/step - loss: 0.7998 - accuracy: 0.5692 - val_loss: 0.6523 - val_accuracy: 0.8860
Epoch 2/50
15/15 [==============================] - 0s 9ms/step - loss: 0.3862 - accuracy: 0.8374 - val_loss: 0.5956 - val_accuracy: 0.9123
Epoch 3/50
15/15 [==============================] - 0s 9ms/step - loss: 0.2641 - accuracy: 0.8923 - val_loss: 0.5469 - val_accuracy: 0.9211
Epoch 4/50
15/15 [==============================] - 0s 9ms/step - loss: 0.2129 - accuracy: 0.9253 - val_loss: 0.5033 - val_accuracy: 0.9123
Epoch 5/50
15/15 [==============================] - 0s 9ms/step - loss: 0.1816 - accuracy: 0.9429 - val_loss: 0.4654 - val_accuracy: 0.9123
Epoch 6/50
15/15 [==============================] - 0s 9ms/step - loss: 0.1699 - accuracy: 0.9407 - val_loss: 0.4302 - val_accuracy: 0.9123
Epoch 7/50
15/15 [==============================] - 0s 9ms/step - loss: 0.1599 - accuracy: 0.9297 - val_loss: 0.3969 - val_accuracy: 0.9123
Epoch 8/50
15/15 [=

In [ ]:
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [ ]:
print(cancer['target_names'][int(y_pred[5])]), print(y_test[5])

benign
1


(None, None)

In [ ]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
cm = confusion_matrix(y_pred, y_test)

In [ ]:
cm

array([[44,  1],
       [ 3, 66]])

In [ ]:
acc_score = accuracy_score(y_pred, y_test)
acc_score

0.9649122807017544